# Generated by Django 4.0.1 on 2022-05-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('college', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LoginInfoKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('college', models.CharField(max_length=500)),
                ('key', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
